### ISSUE TITLE
npm update failed

### ISSUE THREAD

**Issue by floriannagel** [nascentdigital/nd-geohash-core#1]
Hi, i just found your Library and i'm thrilled about it. I have no problems in my local environment. But in the Cloud (AWS Beanstalk) and other folks can't install the npm.

```
Application update failed at 2016-10-28T10:35:51Z with exit status 1 and error: Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/50npm.sh failed.

+ /opt/elasticbeanstalk/containerfiles/ebnode.py --action npm-install

> kerberos@0.0.21 install /tmp/deployment/application/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! stack at Error (native)
gyp ERR! System Linux 4.4.23-31.54.amzn1.x86_64
gyp ERR! command "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/deployment/application/node_modules/kerberos
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

> nd-geohash-core@0.4.1 install /tmp/deployment/application/node_modules/nd-geohash-core
> node-pre-gyp reinstall --fallback-to-build

[nd-geohash-core] Removing "/tmp/deployment/application/node_modules/nd-geohash-core/build/Release"
node-pre-gyp ERR! clean error 
node-pre-gyp ERR! stack Error: EACCES: permission denied, rmdir '/tmp/deployment/application/node_modules/nd-geohash-core/build/Release'
node-pre-gyp ERR! stack at Error (native)
node-pre-gyp ERR! System Linux 4.4.23-31.54.amzn1.x86_64
node-pre-gyp ERR! command "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/node" "/tmp/deployment/application/node_modules/nd-geohash-core/node_modules/.bin/node-pre-gyp" "reinstall" "--fallback-to-build"
node-pre-gyp ERR! cwd /tmp/deployment/application/node_modules/nd-geohash-core
node-pre-gyp ERR! node -v v6.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok 
EACCES: permission denied, rmdir '/tmp/deployment/application/node_modules/nd-geohash-core/build/Release'

npm ERR! Linux 4.4.23-31.54.amzn1.x86_64
npm ERR! argv "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/npm" "--production" "rebuild"
npm ERR! node v6.9.1
npm ERR! npm v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! nd-geohash-core@0.4.1 install: `node-pre-gyp reinstall --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nd-geohash-core@0.4.1 install script 'node-pre-gyp reinstall --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nd-geohash-core package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-pre-gyp reinstall --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs nd-geohash-core
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls nd-geohash-core
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /tmp/deployment/application/npm-debug.log
Running npm install: /opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/npm
Setting npm config jobs to 1
npm config jobs set to 1
Running npm with --production flag
Failed to run npm install. Snapshot logs for more details.
Traceback (most recent call last):
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 695, in 
main()
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 677, in main
node_version_manager.run_npm_install(options.app_path)
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 136, in run_npm_install
self.npm_install(bin_path, self.config_manager.get_container_config('app_staging_dir'))
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 180, in npm_install
raise e
```

**Comment by floriannagel** [comment]
```
> nd-geohash-core@0.4.1 install /home/rof/src/github.com/something/node_modules/nd-geohash-core
> node-pre-gyp reinstall --fallback-to-build

[nd-geohash-core] Removing "/home/rof/src/github.com/something/node_modules/nd-geohash-core/build/Release"
node-pre-gyp ERR! Tried to download: https://nascentdigital.com/nd-geohash-core/v0.4.1/node-v11-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for nd-geohash-core@0.4.1 and node@0.10.48 (node-v11 ABI) (falling back to source compile with node-gyp) 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/rof/src/github.com/something/node_modules/nd-geohash-core/build'
CXX(target) Release/obj.target/_nd-geohash-core/src/addon.o
CXX(target) Release/obj.target/_nd-geohash-core/src/Geohash.o
In file included from ../src/Geohash.cc:2:0:
../src/GeohashRange.h:5:22: fatal error: S2CellId.h: No such file or directory
#include "S2CellId.h"
^
compilation terminated.
make: *** [Release/obj.target/_nd-geohash-core/src/Geohash.o] Error 1
make: Leaving directory `/home/rof/src/github.com/something/node_modules/nd-geohash-core/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/rof/src/github.com/something/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.2.0-42-generic
gyp ERR! command "/home/rof/.nvm/v0.10.48/bin/node" "/home/rof/src/github.com/something/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/rof/src/github.com/something/node_modules/nd-geohash-core/build/Release/_nd-geohash-core.node" "--module_name=_nd-geohash-core" "--module_path=/home/rof/src/github.com/something/node_modules/nd-geohash-core/build/Release"
gyp ERR! cwd /home/rof/src/github.com/something/node_modules/nd-geohash-core
gyp ERR! node -v v0.10.48
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

Can you please help me with this?
